name: cooler_binder
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
- python=3.6
- six
- nose
- mock
- numpy
- scipy
- cython
- h5py
- pandas
- numba
- cytoolz
- jupyter
- ipywidgets
- dask
- matplotlib
- seaborn
- pysam
- pyfaidx
- pairix
- pip>=7.1
- pip:
  - https://bitbucket.org/mirnylab/mirnylib/get/tip.tar.gz
  - cooler

