name: cooler_binder
channels:
  - conda-forge
  - defaults
  - r
  - bioconda
dependencies:
- python=3.5
- six
- nose
- mock
- numpy
- scipy
- cython
- h5py
- pandas
- dask
- matplotlib
- seaborn
- pysam
- pyfaidx
- pip>=7.1
- pip:
  - https://bitbucket.org/mirnylab/mirnylib/get/tip.tar.gz
  - git+git://github.com/mirnylab/cooler.git

